# Generated by Django 3.0 on 2020-05-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index_code', models.CharField(db_index=True, max_length=16)),
                ('index_name', models.CharField(max_length=32)),
                ('index_data_table', models.CharField(max_length=32)),
                ('index_data_fund', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('last_update_date', models.DateField()),
                ('data_source', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'index_info',
            },
        ),
    ]
